name: generate pacman game

on:
  schedule: # Run automatically every 24 hours
    - cron: '0 0 */24 * *'  # Runs daily at 00:00 UTC
  workflow_dispatch: # Allows manual triggering
  push: # Runs on every push to the main branch
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          # Optional: Specify output directory if needed
          # output_dir: ./dist  # Uncomment and adjust if the action supports this

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: .  # Use root directory since the SVG is generated there by default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
